name: my-s3-bucket
metadata:
  app_metadata1: value1
  app_metadata2: value2
resources:
  - name: my-s3-bucket
    kind: terraform/aws
    metadata:
      resource_metadata1: value1
      resource_metadata2: value1
    properties:
      provider_properties:
          region: ${region}
          profile: ${profile}
      module_properties:
        source: cloudposse/s3-bucket/aws
        version: 4.10.0
        name: my-s3-bucket-olegz-${env}-2
        s3_object_ownership: BucketOwnerEnforced
        enabled: true
        user_enabled: false
        versioning_enabled: true
  # - name: my-s3-bucket-2
  #   kind: aws/s3_bucket
  #   depends_on:
  #     - my-s3-bucket
  #   metadata:
  #     resource_metadata1: value1
  #     resource_metadata2: value1
  #   properties:
  #     bucket_name: ${my-s3-bucket.properties.bucket_name}-${env}
  #     region: ${region}
  #     subitem:
  #       key: ${region}